spring:
  application:
    name: demo
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  r2dbc:
    url: r2dbc:h2:mem:///testdb
    username: sa
    password:
  sql:
    init:
      mode: always
  h2:
    console:
      port: 9090
      enabled: true

jwt:
  secret: aosdikgjalsdkgjasdlgkjqwieuqwidjaskdlaksjcvalsjlediawjqasdasgasvasvasadfasfvasfvasd

cookie:
  secure: false